### ISSUE TITLE
How to set a url to be act like a reverse proxy

### ISSUE THREAD

**Issue by choudh2011** [mitre/HTTP-Proxy-Servlet#188]
I'd like to set a URL, /xxx/rabbitmq, act as a reverse proxy.
I mean all relative URL will base on /xxx/rabbitmq, however, the relative URLs change to /xxx/{relative_url}.
Thus, I can't get the correct and complete pages.
Following is my web.xml.
```
<servlet>
  <servlet-name>clusterProxy</servlet-name>
  <servlet-class>org.mitre.dsmiley.httpproxy.URITemplateProxyServlet</servlet-class>
  <init-param>
    <param-name>targetUri</param-name>
    <param-value>http://127.0.0.1:15672</param-value>
  </init-param>
</servlet>

<servlet-mapping>
  <servlet-name>clusterProxy</servlet-name>
  <url-pattern>/rabbitmq/*</url-pattern>
</servlet-mapping>

```

**Comment by dsmiley** [comment]
Why Use the URITemplate version?  I think `org.mitre.dsmiley.httpproxy.ProxyServlet` should work.
Otherwise I'm not really sure.  Admittedly I don't offer much support here these days.  I'm not sure quite sure what you're saying doesn't work but you might want to look at it from the proxy's perspective and more concretely say what your expectation is for a given configuration and input -- almost like a test.

**Comment by choudh2011** [comment]
The root cause is that there is another proxy in front of my tomcat. I set the proxy correctly then I have no problem and I'm done what I want. Thanks.
